dist: bionic
addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /'
      key_url: 'https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_18.04/Release.key'
    packages:
    - buildah
language: go
go:
- 1.14.x
cache:
  directories:
  - "${GOPATH}/pkg/mod"
  - "${GOPATH}/pkg/sumdb"
env:
  global:
  - GO111MODULE: 'on'
  - RELAY_EMAIL: team-relay-ops@puppet.com
  - secure: QL8vS5o6H3/WyqelaJprcwUA/troTk67YeTs0m362327EsdQXEVnk0dlCcT+j460ALGgJ8l+j+Ywx9StFwx5FWOdvA02QMyiM1rNXtdJREACQe+3rODxwaoc+wMiX31Nnahg5uu/w3nXjY6wZpNto6pISZaSHxblm90uAGSlCKDd5PeEkH0CkQMDgN7JqwYeWohqXgIhkq/qTmnbNfwE4UTXo3/o3X9JqrZJV1aH1R0HKhH2qCM9BxldvnTVp36444qM8r/UGiZEjoqp2u1XZ47wmRMdKVcSSw013n6yhdT9vrGaCPKrGXVQt00/lU9TpCW0SR5CPsyMPhqIRI9EDKT3WwltV/t0x1ofuP3G2yEfoFxsktxQs4tF099u4QnTL74vat7KnnCX9QHkzONk0bUv9SzF8a9Z0bO9SDfG/pV+4f9DL6dTiC2Tp06kr7VEHkdURe/Xg+t/CzZ64derhmDxciiI+4wqq8xhktFcdMEBiRxs84ToccohzJrYyLFJ9HowKp4EIb8UYW5f5umN6iLUN/dNqyU8BXLo3zhw9plIT6GT4hlFdX8mFTKTAIkSUlezYzOlR2/j6x3yd3RWAFDFdGpQtTh3C306cvzkr0Ng2f+H3qUZBX8MskK/oK9sOM8nv7c9DLZOTxOdHPfDPm4751uhqZb5t+GTCE3va1Q=
  - DOCKER_CONFIG: /tmp/.docker
  - DOCKERHUB_USERNAME: relayshro
  - secure: X/13IRN9ynZw6NNS/ydT9TSW7tk9AFHocQwA2jOXfvmid2tE+AXTa3NMGnvsHlfWAORevYpLCl8I7P8yu+MbQT+sCgTZ/B1NUpqx7v13FZiK8/nYHi/Ne7+upnRLQa95aKPXaet2qgv1k+uFs3WKiqCRE1oFLCbBf8RtpT7+JinR9FaZ63nVyX4pI3yFvp72CjsPOqHnf9MPP/qZ1A2ZdBDydzdkdgaq2KbkkurJlbCfm3iJ+QMookA1/SA+4lb9xCqJ5oigAgk4L6NOl7EEhSIAcHBhbNvOpeJo52kJepeHsfa/FD6eNUUMIuKPgqH+QyCg+s9ZAy5ZemxI2W5JoUeZGKYINMfUyntckpUtE6R2pLlD1HWsNS1ff40VGOuYCxBmwPlfWzwdAPxZazeYJ68XJi37hco37G8uD5FHbMFxlG64vONoJGdLZCkX7OhiiHd3WYEXD6PmVt82+0XnpNgvPFr8sEXOaRSxcUX+VUt8f/r/Ko1zg9KKGwn3FdRfp8xF0hPoguzDMlNd5fW+bVY71tdETwuPVnkUAjKrlPL5N5lrLr0xwfWEwoEL+SwJDe011h8rRdNQiswzQ5Eqna3ZTDR96aTdKiagN+XaCUEKip7hO4POebs/W5iLxQshZn/BgeS1qhoA/5PFTKokutUuWNFw8oJafZKBCDcsipc=
install:
- mkdir -p "${DOCKER_CONFIG}"
- echo '{}' >"${DOCKER_CONFIG}/config.json"
- docker login --username "${DOCKERHUB_USERNAME}" --password-stdin <<<"${DOCKERHUB_PASSWORD}"
jobs:
  include:
  - &test-all
    stage: test
    env:
    - K3D_K3S_VERSION: v1.17.15-k3s1
    before_script:
    - ( cd; GO111MODULE=on go get github.com/rancher/k3d/v3@v3.4.0 gotest.tools/gotestsum )
    - export KUBECONFIG=/tmp/kubeconfig-test
    - |
      hack/k3d/start --no-rollback --verbose --volume="${DOCKER_CONFIG}/config.json:/var/lib/kubelet/config.json" || {
        docker logs k3d-relay-core-test-server-0
        exit 1
      }
    script:
    - RELAY_TEST_E2E_KUBECONFIG="${KUBECONFIG}" RELAY_TEST_E2E_GVISOR_HANDLER=runsc ./scripts/ci test
  - <<: *test-all
    env:
    - K3D_K3S_VERSION: v1.18.13-k3s1
  - <<: *test-all
    env:
    - K3D_K3S_VERSION: v1.19.5-k3s1
  - stage: build
    before_script:
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk;
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com |
      bash; fi
    - source "$HOME"/google-cloud-sdk/path.bash.inc
    - openssl aes-256-cbc -K $encrypted_35392154f715_key -iv $encrypted_35392154f715_iv
      -in scripts/nebula-gcloud-service-account.json.enc -out scripts/nebula-gcloud-service-account.json
      -d
    - gcloud auth activate-service-account --key-file scripts/nebula-gcloud-service-account.json
    - gcloud --quiet auth configure-docker
    script:
    - "./scripts/ci build"
    - "./scripts/ci release"
  - stage: deploy
    script:
    - "./scripts/ci deploy"
